name: Another workflow to mock being called in backend workflows

on: 
  workflow_call:
    inputs:
      filePath:
        required: false
        description: 'Path of YAML or env file to override'
        default: ''
      keyValueObject:
        required: false
        description: 'Object of existing keys and values to override existing values'
        default: ''

jobs:
  job3:
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: input file path
        run: echo ${{ github.event.inputs.filePath }}
      
      - name: input key val map
        run: echo ${{ github.event.inputs.keyValueObject }}
  
  job4:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send to override
        uses: ./
        with:
          filePath: './helm/marketplace-coordinator/environments/nonproduction/application.yaml'
          keyValueObject: ${{ toJson(needs.job1.outputs) }}