name: Test workflow

on: 
  pull_request:
  workflow_dispatch:
    inputs:
      addEnvVar:
        type: boolean
        description: 'Add test env var'
        default: false
        required: true
      filePath:
        description: 'mock P8P URL'
        default: 'https://whatever.com'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ENV_VAR: ${{ steps.env_var.outputs.ENV_VAR }}
      yaml.prop: '///\\\--__...[]=()'
    steps:
      - name: add env var
        if: ${{ github.event.inputs.addEnvVar }}
        id: env_var
        run: echo "::set-output name=ENV_VAR::Change again!"

  job2:
    uses: ./.github/workflows/mock.yaml
    needs: job1
    with:
      filePath: ${{ github.event.inputs.filePath }}
      keyValueObject: ${{ toJson(needs.job1.outputs) }}