name: Test workflow

on:
  workflow_dispatch:
    inputs:
      addVar:
        required: false
        description: test var conditions
        default: false
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      ENV_VAR: ${{ steps.env_var.outputs.ENV_VAR }}
      yaml.prop: '///\\\--__...[]=()'
    steps:
      - name: add env var
        if: ${{ github.event.inputs.addVar }}
        id: env_var
        run: echo "::set-output name=ENV_VAR::Change again!"

  job2:
    runs-on: ubuntu-latest
    uses: abardaipax8/buildtime-value-overrider/.github/workflows/anotherWorkflow.yml@test-pr
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: send to mock backend workflow
        uses: ./.github/workflows/anotherWorkflow.yml
        with:
          filePath: './helm/marketplace-coordinator/environments/nonproduction/application.yaml'
          keyValueObject: ${{ toJson(needs.job1.outputs) }}
