name: Test workflow

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      keyValues: ${{ steps.json_map.outputs.keyVals }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create value outputs
        id: run_outputs
        run: |
          echo "::set-output name=ENV_VAR::Hello Vars!"
          echo "::set-output name=yaml.prop::!@#$%^&*()-=_+;':""',./<>?`~`"
          echo "::set-output name=ENV_VAR2::Hello Vars!"
          echo "::set-output name=ENV_VAR3::Hello Vars!"
          echo "::set-output name=ENV_VAR4::Hello Vars!"

      - name: Join key and values
        id: json_map
        env:
          JSON: ${{ toJson(steps.run_outputs.outputs) }}
        run: echo "::set-output name=keyVals::$($JSON)"

      - name: Send to override
        uses: ./
        with:
          filePath: './helm/marketplace-coordinator/environments/nonproduction/application.yaml'
          keyValueObject: ${{ steps.json_map.outputs.keyVals }}