name: Test workflow

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      keyValues: ${{ toJson(steps.run_outputs.outputs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create value outputs
        id: run_outputs
        run: |
          echo "::set-output name=ENV_VAR::Hello Vars!"
          echo "::set-output name=yaml.prop::!@#$%^&*()-=_+;':""',./<>?`~`"
          echo "::set-output name=ENV_VAR2::Hello Vars!"
          echo "::set-output name=ENV_VAR3::Hello Vars!"
          echo "::set-output name=ENV_VAR4::Hello Vars!"

      - name: Send to override
        uses: ./
        with:
          filePath: './helm/marketplace-coordinator/environments/nonproduction/application.yaml'
          keyValueObject: ${{ toJson(steps.run_outputs.outputs) }}


  job1:
    runs-on: ubuntu-latest
    outputs:
      ENV_VAR: Hello Vars!
      yaml.prop: '///\\\--__...[]=()'
    steps:
      - name: update p8p endpoint
        if: true
        run: echo "::set-output name=ENV_VAR44::Hello Vars!"
      - run: echo "Setting up Key-Val combinations"

  job2:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Join key and values
      # env:
      #   JSON: ${{ toJson() }}
      run: echo ${{ needs.test.outputs.keyValues }}