name: Test workflow

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      keyValues: ${{ toJson(steps.run_outputs.outputs) }}
    steps:
      - name: Create value outputs
        id: run_outputs
        run: |
          echo "::set-output name=ENV_VAR::Hello Vars!"

          if false
            then echo "::set-output name=yaml.prop::!@#$%^&*()-=_+;':""',./<>?`~`"
          fi

          echo "::set-output name=ENV_VAR2::Hello Vars!"
          echo "::set-output name=ENV_VAR3::Hello Vars!"
          echo "::set-output name=ENV_VAR4::Hello Vars!"

  job1:
    runs-on: ubuntu-latest
    outputs:
      ENV_VAR: Hello Vars!
      yaml.prop: '///\\\--__...[]=()'
    steps:
      - name: update p8p endpoint
        if: true
        run: echo "::set-output name=ENV_VAR::Change please!"
      - run: echo "Setting up Key-Val combinations"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          JSON: ${{ toJson(needs.job1.outputs) }}
        run: echo $JSON

  job2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Send to override
        uses: ./
        with:
          filePath: './helm/marketplace-coordinator/environments/nonproduction/application.yaml'
          keyValueObject: ${{ toJson(needs.test.outputs.keyValues) }}
